### ISSUE TITLE
[Update] Paper Tales

### ISSUE THREAD

**Issue by Iconos** [thedeviousdev/Card-Sleeves#1]
**Game Name:** Paper Tales
**Board Game Geek URL:** https://boardgamegeek.com/boardgame/217861/paper-tales
**Year:** (if possible)

**Sleeve Size #1**
**Quantity:** 111
**Width (mm):** 63mm 
**Height (mm):** 88mm

**Comment by thedeviousdev** [comment]
Hey thank you so much for posting here, it will be much easier to track. (I hope you don't mind, I updated your post to follow the template)

Added!

**Comment by Iconos** [comment]
**Game Name:** Paper Tales: Beyond the Gates (Expansion)
**Board Game Geek URL:** https://boardgamegeek.com/boardgameexpansion/245473/paper-tales-beyond-gates
**Year:** 2018

**Sleeve Size #1**
**Quantity:** 99
**Width (mm):** 63mm 
**Height (mm):** 88mm
