### ISSUE TITLE
Stuffed Fables

### ISSUE THREAD

**Issue by LordWicki** [thedeviousdev/Card-Sleeves#10]
The Fantasy Flight Mini Sleeves should be Yellow, not Red.  The red sleeves are too big, and the game refers to the yellow on the back of the box as well.

**Comment by thedeviousdev** [comment]
Thanks for that update! I've submitted it to the BGG list here: https://boardgamegeek.com/geeklist/164572/item/6046583?commentid=9616794#comment9616794
