### ISSUE TITLE
[Request] Run Fight or Die: Reloaded

### ISSUE THREAD

**Issue by netminder69** [thedeviousdev/Card-Sleeves#13]
Game Name: Run Fight or Die: Reloaded
Board Game Geek URL: https://boardgamegeek.com/boardgame/257096/run-fight-or-die-reloaded
Year/Edition: 2019

Sleeve Size 1
Quantity: 93
Width (mm): 63.5 mm
Height (mm): 88 mm

Sleeve Size 2
Quantity: 45
Width (mm): 41 mm
Height (mm): 63 mm

The Kickstarter edition has 11 extra cards: 7 of Sleeve type 1, 4 of sleeve type 2. Not sure how to format that in here.

**Comment by thedeviousdev** [comment]
Thanks! Updated.
