### ISSUE TITLE
[Update] Atelier: The Painter's Studio

### ISSUE THREAD

**Issue by netminder69** [thedeviousdev/Card-Sleeves#14]
Game Name: Atelier: The Painter's Studio
BGG URL: https://boardgamegeek.com/boardgame/273284/atelier-painters-studio
Year: 2019

Sleeve Size 1
Quantity: 16
Width: 63.5 mm
Height: 88 mm

Sleeve Size 2
Quantity: 40
Width: 70 mm
Height: 120 mm

**Comment by thedeviousdev** [comment]
Updated, thanks!
