### ISSUE TITLE
[Update] Innovation: Artifacts of History

### ISSUE THREAD

**Issue by gchambers419** [thedeviousdev/Card-Sleeves#3]
**Game Name:** Innovation: Artifacts of History
**Board Game Geek URL:** https://boardgamegeek.com/boardgameexpansion/185796/innovation-artifacts-history
**Yea/Edition:** 3rd

**Sleeve Size 1**
**Quantity:**  110
**Width (mm):** 63
**Height (mm):** 88

**Comment by thedeviousdev** [comment]
Added!
