### ISSUE TITLE
[Update] Innovation: Cities of Destiny

### ISSUE THREAD

**Issue by gchambers419** [thedeviousdev/Card-Sleeves#4]
**Game Name:** Innovations: Artifacts of History
**Board Game Geek URL:** https://boardgamegeek.com/boardgameexpansion/150669/innovation-cities-destiny
**Yea/Edition:** 3rd

**Sleeve Size 1**
**Quantity:**  110
**Width (mm):** 63
**Height (mm):** 88

**Comment by thedeviousdev** [comment]
Added!
