### ISSUE TITLE
[Request] Sid Meier's Civilization: The Board Game

### ISSUE THREAD

**Issue by Jolken71** [thedeviousdev/Card-Sleeves#5]
Sid Meier's Civilization: The Board Game
https://boardgamegeek.com/boardgame/77130/sid-meiers-civilization-board-game
2010

**Comment by thedeviousdev** [comment]
Added!
```
Sid Meier's Civilization: The Board Game
41mm x 63mm
224
65mm x 65mm
55
```

Reference: https://boardgamegeek.com/geeklist/164572/item/4167285#item4167285
