### ISSUE TITLE
[Update] Unearth

### ISSUE THREAD

**Issue by Iconos** [thedeviousdev/Card-Sleeves#6]
Game Name: Unearth
Board Game Geek URL: https://boardgamegeek.com/boardgame/217085/unearth
Year: 2017

Sleeve Size 1
Quantity: 30
Width (mm): 70mm
Height (mm): 120mm

Sleeve Size 2
Quantity: 21
Width (mm): 36mm
Height (mm): 88mm

Sleeve Size 3
Quantity: 38
Width (mm): 43mm
Height (mm): 65mm

**Comment by thedeviousdev** [comment]
Ooh, like the artwork of this one... Added!
